# Generated by Django 4.2.30 on 2026-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='farm_story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
