# Generated by Django 4.2.29 on 2026-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
