# Generated by Django 4.2.29 on 2026-03-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PREPARING', 'Preparing'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='PAID', max_length=20),
        ),
    ]
