# Generated by Django 4.2.30 on 2026-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_best_before_date_product_harvest_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
    ]
