# Generated by Django 4.2.30 on 2026-04-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_organic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('SEASONAL', 'Seasonal'), ('LIMITED', 'Limited Stock')], default='IN_STOCK', max_length=20),
        ),
    ]
