# Generated by Django 4.2.30 on 2026-04-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='harvest_dates',
            new_name='harvest_date',
        ),
    ]
