# Generated by Django 4.2.30 on 2026-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_harvest_dates_product_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage e.g. 20 for 20%'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_surplus',
            field=models.BooleanField(default=False),
        ),
    ]
