# Generated by Django 4.2.30 on 2026-05-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_discount_percent_product_is_surplus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_from',
            field=models.DateField(blank=True, help_text='Date from which this product is available for collection/delivery', null=True),
        ),
    ]
