# Generated by Django 4.2.30 on 2026-05-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_settlement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settlement',
        ),
    ]
