# Generated by Django 4.2.30 on 2026-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_remove_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Remove surplus discount when stock falls to this level'),
        ),
        migrations.AddField(
            model_name='product',
            name='overstock_threshold',
            field=models.PositiveIntegerField(default=20, help_text='Stock level where surplus discount can apply'),
        ),
    ]
